language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        # allow failure for Php >= 5.6
        - php: 7
        - php: hhvm
    fast_finish: true

install:
  composer install --prefer-source

# before_script:
#     - mkdir -p build/logs

script: ./vendor/bin/phpunit

# after_script:
#     - php vendor/bin/coveralls
